import { StyleSheet } from 'react-native'

const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#00000088',
  },
  modalContent: {
    alignItems: 'center',
    width: '100%',
    height: '100%',
    padding: 20,
    backgroundColor: '#3f3c39',
    borderRadius: 20,
  },
  nameSection: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: '3%',
  },
  specieIcon: {
    width: 25,
    height: 25,
    marginRight: 10,
    resizeMode: 'contain',
  },
  modalTitle: {
    fontSize: 28,
    fontWeight: 'bold',
  },
  modalImage: {
      width: 150,
      height: 140,
    marginBottom: 20,
  },
  quoteBox: {
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    borderRadius: 16,
  },
  quoteText: {
    color: '#e9e9e9',
    justifyContent: 'center',
    alignContent: 'center',
    alignSelf: 'center',
    alignContent: 'center',
    padding: 10,
    margin: 7,
    marginBottom: -5,
    marginTop: -10,
    fontSize: 17,
    fontWeight: 'bold',
  },
  iconSection: {
    borderRadius: 20,
    margin: 13,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  iconTextRow: {
    margin: 6,
    borderRadius: 32,
    paddingTop: 9,
    paddingBottom: 9,
    paddingLeft: 14,
    paddingRight: 14,
    flexDirection: 'row',
    alignItems: 'center',
    width: '45%',
    shadowColor: '#151615',
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.37,
    shadowRadius: 8,
  },
  infoText: {
    paddingLeft: 10,
    fontSize: 12,
    fontWeight: 'bold',
    shadowColor: '#151615',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.37,
    shadowRadius: 5,
  },
  vilHomeSection: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 24,
    padding: 20,
    shadowColor: '#151615',
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.37,
    shadowRadius: 8,
  },
  vilHomeText: {
    flex: 1,
    justifyContent: 'flex-start',
    padding: 20,
    fontWeight: 'bold',
    fontSize: 25,
    color: '#e9e9e9',
    marginBottom: 10,
    shadowColor: '#151615',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.37,
    shadowRadius: 8,
  },
  vilHomeImage: {
    width: 150,
    height: 140,
    shadowColor: '#151615',
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.37,
    shadowRadius: 8,
  },
  btn: {
    padding: 15,
    alignContent: 'center',
    alignItems: 'center',
  },
  btnText: {
    color: '#e9e9e9',
    fontSize: 27,
    fontWeight: 'bold',
    marginTop: 20,
  }
})

export default styles