const Icons = {
  alligator: require('../assets/species-icons/alligator-icon.png'),
  anteater: require('../assets/species-icons/anteater-icon.png'),
  bear: require('../assets/species-icons/bear-icon.png'),
  bear_cub: require('../assets/species-icons/bearcub-icon.png'),
  bird: require('../assets/species-icons/bird-icon.png'),
  bovine: require('../assets/species-icons/bovine-icon.png'),
  cat: require('../assets/species-icons/cat-icon.png'),
  chicken: require('../assets/species-icons/chicken-icon.png'),
  deer: require('../assets/species-icons/deer-icon.png'),
  dog: require('../assets/species-icons/dog-icon.png'),
  duck: require('../assets/species-icons/duck-icon.png'),
  eagle: require('../assets/species-icons/eagle-icon.png'),
  elephant: require('../assets/species-icons/elephant-icon.png'),
  frog: require('../assets/species-icons/frog-icon.png'),
  goat: require('../assets/species-icons/goat-icon.png'),
  gorilla: require('../assets/species-icons/gorilla-icon.png'),
  hamster: require('../assets/species-icons/hamster-icon.png'),
  hippo: require('../assets/species-icons/hippo-icon.png'),
  horse: require('../assets/species-icons/horse-icon.png'),
  kangaroo: require('../assets/species-icons/kangaroo-icon.png'),
  koala: require('../assets/species-icons/koala-icon.png'),
  lion: require('../assets/species-icons/lion-icon.png'),
  monkey: require('../assets/species-icons/monkey-icon.png'),
  mouse: require('../assets/species-icons/mouse-icon.png'),
  octopus: require('../assets/species-icons/octopus-icon.png'),
  ostrich: require('../assets/species-icons/ostrich-icon.png'),
  penguin: require('../assets/species-icons/penguin-icon.png'),
  pig: require('../assets/species-icons/pig-icon.png'),
  rabbit: require('../assets/species-icons/rabbit-icon.png'),
  rhinoceros: require('../assets/species-icons/rhinoceros-icon.png'),
  sheep: require('../assets/species-icons/sheep-icon.png'),
  special: require('../assets/species-icons/special-icon.png'),
  squirrel: require('../assets/species-icons/squirrel-icon.png'),
  tiger: require('../assets/species-icons/tiger-icon.png'),
  wolf: require('../assets/species-icons/wolf-icon.png'),
}

export default Icons